### ISSUE TITLE
Highlight does not work with Kannada

### ISSUE THREAD

**Issue by alaymari** [cpierquet/highlightx#1]
I am trying to use this package to highlight text in my documents. It works fine with English text (maybe other European languages too, I am not sure). When I tried to use it with Kannada, a language of India, it fails to highlight the text.

I am giving a MWE as well as a screenshot:

```
\documentclass{article}                                                 
\usepackage{highlightx}                                                 
\usepackage{fontspec}                                                   
\usepackage{polyglossia}                                                
\setdefaultlanguage{kannada}                                            
\setotherlanguage{english}                                              
\setmainfont[Script=Kannada]{Noto Sans Kannada}                         
                                                                        
\newcommand{\HL}[1]{\SurlignerTexte{#1}}                                
                                                                        
\begin{document}                                                        
                                                                        
ಕರ್ನಾಟಕ ನಾಡು ಮತ್ತು \HL{ಆ ನಾಡಿನ ಜನ ಹಾಗೂ ಅವರಾಡುವ ಭಾಷೆ}.                       
                                                                        
\textenglish{Some text \HL{in English highlighted}}.                    
                                                                        
\end{document} 
```

![20231105-113907](https://github.com/cpierquet/highlightx/assets/34280138/040a4ef5-137e-44e4-af7d-b76384140b4c)

Can this package be changed / improved to support languages other than English et al.?

**Comment by cpierquet** [comment]
Hi- sadly, `soul`, the package used to create `highlightx` don't seems to work with other characters than english...
If you try your code with `soul` commands it'll be the same ;-(

![image](https://github.com/cpierquet/highlightx/assets/45103962/3bdfed70-ff97-4e5f-95a4-793ff288aca6)
